go:
    cgo: true
repository:
    path: github.com/RobustPerception/azure_metrics_exporter
build:
    binaries:
        - name: azure_metrics_exporter
    flags: -a -tags 'netgo static_build'
    ldflags: |
      -w -s -extldflags -static
tarball:
    files:
        - README.md
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - linux/arm
        - linux/arm64
        - darwin/amd64
        - darwin/386
